---
- name: Start Azure VM
  hosts: localhost
  tasks:
    - name: Log in to Azure
      shell: az login ${{ secrets.LOGINCREDENTIALSAZ }}
      register: login_output

    - name: Start the VM
      shell: az vm start --resource-group B2C6A --name DevOpsB2aV5
      when: login_output is succeeded

- name: Setup and start frontend application
  hosts: frontend
  tasks:
    - name: Change to frontend25 directory
      shell: cd /home/${{ secrets.ADMIN_USERNAME_AZ }}/frontend25/B2C6_B2A_Frontend
      args:
        chdir: /home/${{ secrets.ADMIN_USERNAME_AZ }}

    - name: Start frontend application
      shell: sudo npm run dev
      args:
        chdir: /home/${{ secrets.ADMIN_USERNAME_AZ }}/frontend25/B2C6_B2A_Frontend
      become: true
