---
- name: Start Azure VM
  hosts: localhost
  tasks:
    - name: Log in to Azure
      shell: az login ${{ secrets.LOGINCREDENTIALSAZ }}
      register: login_output

    - name: Start the VM
      shell: az vm start --resource-group B2C6A --name DevOpsB2aVmV3
      when: login_output is succeeded

- name: Setup and start backend application
  hosts: backend
  tasks:
    - name: Activate virtual environment and start backend application
      shell:
        cmd: |
          /home/${{ secrets.ADMIN_USERNAME_AZ }}/myproject2/venv/bin/python3 /home/${{ secrets.ADMIN_USERNAME_AZ }}/myproject2/Backend_B2A.py
      become: true
